#! /usr/bin/zsh
if [[ `/usr/bin/xinput --list-props 12 | awk ' /Device Enabled/ { print $NF} ' ` = 0 ]] 
        then /usr/bin/xinput set-prop 12 "Device Enabled" 1
else /usr/bin/xinput set-prop 12 "Device Enabled" 0
fi
