#! /usr/bin/zsh
if [[ `/usr/bin/xinput --list-props "SynPS/2 Synaptics TouchPad"| awk ' /Device Enabled/ { print $NF} '` = 0 ]] 
        then /usr/bin/xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1
else /usr/bin/xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
fi
